# Generated by Django 5.0.1 on 2026-07-12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0006_remove_scheduledjob_last_next_run_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledJobRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_for', models.DateTimeField(verbose_name='计划触发时间')),
                ('status', models.CharField(choices=[('starting', '启动中'), ('launched', '已启动'), ('failed', '启动失败')], default='starting', max_length=20, verbose_name='启动状态')),
                ('error_message', models.TextField(blank=True, verbose_name='启动错误')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('scheduled_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='scheduler.scheduledjob', verbose_name='定时作业')),
            ],
            options={
                'verbose_name': '定时作业运行',
                'verbose_name_plural': '定时作业运行',
                'ordering': ['-scheduled_for'],
            },
        ),
        migrations.AddConstraint(
            model_name='scheduledjobrun',
            constraint=models.UniqueConstraint(fields=('scheduled_job', 'scheduled_for'), name='scheduler_unique_job_scheduled_minute'),
        ),
        migrations.AddIndex(
            model_name='scheduledjobrun',
            index=models.Index(fields=['scheduled_job', '-scheduled_for'], name='scheduler_s_schedul_5e35a7_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledjobrun',
            index=models.Index(fields=['status', '-scheduled_for'], name='scheduler_s_status_bc7dd2_idx'),
        ),
    ]