# Generated by Django 5.0.1 on 2026-07-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0007_scheduledjobrun'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulerLease',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='租约名称')),
                ('holder', models.CharField(max_length=64, verbose_name='持有者')),
                ('expires_at', models.DateTimeField(verbose_name='过期时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '调度器租约',
                'verbose_name_plural': '调度器租约',
            },
        ),
    ]