PYTHON ?= python
MANAGE ?= $(PYTHON) manage.py

E2E_CONTROL_PLANE ?= 1
E2E_REDIS_ADDR ?= 127.0.0.1:6379
E2E_REDIS_PASSWORD ?=
E2E_REDIS_DB ?= 3
E2E_AGENT_SERVER_SECRET ?= e2e-secret
E2E_TEST_PATH ?= apps.agents.tests.test_e2e_control_plane

.PHONY: e2e-control-plane

e2e-control-plane:
	E2E_CONTROL_PLANE=$(E2E_CONTROL_PLANE) \
	E2E_REDIS_ADDR=$(E2E_REDIS_ADDR) \
	E2E_REDIS_PASSWORD=$(E2E_REDIS_PASSWORD) \
	E2E_REDIS_DB=$(E2E_REDIS_DB) \
	E2E_AGENT_SERVER_SECRET=$(E2E_AGENT_SERVER_SECRET) \
	$(MANAGE) test $(E2E_TEST_PATH)
