"""
Django settings for ops_job project.

Generated by 'django-admin startproject' using Django 4.2.23.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-6c1-^k)gceo*z@vs-=(!*yb)=7k)6%87!-*wp8vve8x=e=$-m@'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'simpleui',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # 第三方应用
    'rest_framework',
    'rest_framework_extensions',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'drf_spectacular',
    'django_json_widget',                # json编辑器
    'admin_auto_filters',                # admin自动完成过滤器
    'axes',                              # 登录安全防护
    'django_filters',                    # drf过滤器
    'guardian',                          # 对象级权限管理
    'django_celery_beat',                # celery定时任务
    'django_celery_results',
    'django_extensions',
    'captcha',                           # 验证码
    'health_check',                      # 健康检查
    'health_check.db',                   # 数据库健康检查
    'health_check.contrib.redis',        # redis健康检查
    'health_check.contrib.celery',       # celery健康检查

    # 自定义应用
    'apps.hosts',           # 主机管理
    'apps.job_templates',   # 作业模板
    'apps.executor',        # 执行引擎
    'apps.script_templates', # 脚本模板
    'apps.quick_execute',   # 快速执行
    'apps.scheduler',       # 定时任务
    'apps.accounts',        # 用户权限
    'apps.permissions',     # 权限管理
    'apps.dashboard',       # 仪表盘
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'axes.middleware.AxesMiddleware',     # Axes安全中间件
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ops_job.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ops_job.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django REST Framework 配置
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_PARSER_CLASSES': (
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ),
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',
        'user': '1000/hour'
    },
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# DRF Extensions 配置
REST_FRAMEWORK_EXTENSIONS = {
    'DEFAULT_CACHE_RESPONSE_TIMEOUT': 60 * 15,  # 15分钟缓存
    'DEFAULT_USE_CACHE': 'default',
    'DEFAULT_OBJECT_CACHE_KEY_FUNC': 'rest_framework_extensions.utils.default_object_cache_key_func',
    'DEFAULT_LIST_CACHE_KEY_FUNC': 'rest_framework_extensions.utils.default_list_cache_key_func',
}

# redis 数据库索引配置
REDIS_DB_CACHE = 0  # 用于一般缓存
REDIS_DB_SESSION = 1  # 用于会话存储
REDIS_DB_CELERY = 2  # 用于 Celery
REDIS_DB_CHANNELS = 3  # 用于 Channels

# redis 配置
REDIS_HOST = os.getenv('REDIS_HOST', '123.207.190.53')
REDIS_PORT = os.getenv('REDIS_PORT', '6379')
REDIS_PASSWORD = os.getenv('REDIS_PASSWORD', '913689yhk')

# 缓存配置
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': f"redis://:{REDIS_PASSWORD}@{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB_CACHE}",
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'CONNECTION_POOL_KWARGS': {
                'max_connections': 50,
                'retry_on_timeout': True,
            },
            'COMPRESSOR': 'django_redis.compressors.zlib.ZlibCompressor',
            'IGNORE_EXCEPTIONS': True,
        },
        'KEY_PREFIX': 'ops_job',
        'TIMEOUT': 300,  # 5分钟默认超时
    }
}


from datetime import timedelta

# JWT 配置
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=24),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,

    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    'JWK_URL': None,
    'LEEWAY': 0,

    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',

    'JTI_CLAIM': 'jti',

    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(hours=24),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=7),
}


# celery 配置
CELERY_BROKER_URL = f"redis://:{REDIS_PASSWORD}@{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB_CELERY}"
CELERY_RESULT_BACKEND = 'django-db'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_ENABLE_UTC = True
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30分钟
CELERY_WORKER_CONCURRENCY = 4  # 并发工作进程数
CELERY_WORKER_MAX_TASKS_PER_CHILD = 500  # 每个工作进程最大任务数
CELERY_WORKER_PREFETCH_MULTIPLIER = 4  # 预取任务数
CELERY_TASK_REJECT_ON_WORKER_LOST = True  # worker丢失时拒绝任务
CELERY_TASK_ACKS_LATE = True  # 任务执行完成后才确认
CELERY_TASK_ALWAYS_EAGER = False  # 确保异步执行
CELERY_TASK_EAGER_PROPAGATES = True  # 异常传播
CELERY_WORKER_DISABLE_RATE_LIMITS = True  # 禁用速率限制
CELERY_TASK_IGNORE_RESULT = False  # 不忽略结果

# celery 任务路由
CELERY_TASK_ROUTES = {
    'executor.tasks.*': {'queue': 'executor'},
    'scheduler.tasks.*': {'queue': 'scheduler'},
}

# Health Check 配置
HEALTH_CHECK = {
    'DISK_USAGE_MAX': 90,  # 磁盘使用率阈值
    'MEMORY_MIN': 100,     # 最小可用内存(MB)
}
# Health Check Redis 配置
REDIS_URL = f"redis://:{REDIS_PASSWORD}@{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB_CACHE}"
# Health Check Celery 配置
HEALTHCHECK_CELERY_TIMEOUT = 5.0   # Celery健康检查超时时间(秒)
HEALTHCHECK_CELERY_RESULT_TIMEOUT = 5.0
HEALTHCHECK_CELERY_QUEUE_TIMEOUT = 5.0


# drf_spectacular 配置
SPECTACULAR_SETTINGS = {
    'TITLE': 'OPS Job API',
    'DESCRIPTION': '运维作业平台 API 文档',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'SCHEMA_PATH_PREFIX': '/api/',
    'SWAGGER_UI_SETTINGS': {
        'deepLinking': True,
        'persistAuthorization': True,
        'displayOperationId': True,
    },
    'PREPROCESSING_HOOKS': [
        'drf_spectacular.hooks.preprocess_exclude_path_format',
    ],
    'POSTPROCESSING_HOOKS': [
        'drf_spectacular.hooks.postprocess_schema_enums',
    ],
}

# django-axes 安全配置 + Guardian 对象级权限
AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',  # Axes认证后端
    'django.contrib.auth.backends.ModelBackend',  # Django默认认证后端
    'guardian.backends.ObjectPermissionBackend',  # Guardian对象级权限后端
]

AXES_ENABLED = True
AXES_FAILURE_LIMIT = 5  # 允许的最大失败次数
AXES_LOCK_OUT_AT_FAILURE = True  # 达到限制后锁定
AXES_COOLOFF_TIME = timedelta(minutes=30)  # 锁定时间
AXES_RESET_ON_SUCCESS = True  # 登录成功后重置失败计数
AXES_DISABLE_ACCESS_LOG = False
AXES_ENABLE_ACCESS_FAILURE_LOG = True  # 记录失败访问
# 前后端分离相关配置
AXES_LOCKOUT_PARAMETERS = ["ip_address", ["username", "user_agent"]]  # 锁定字段
AXES_LOCKOUT_CALLABLE = 'utils.responses.account_locked'  # 自定义锁定响应处理
AXES_USERNAME_FORM_FIELD = 'username'  # 用户名字段

# Guardian 配置
GUARDIAN_RAISE_403 = True  # 当权限检查失败时抛出 PermissionDenied
ANONYMOUS_USER_NAME = None  # 禁用匿名用户功能
GUARDIAN_AUTO_PREFETCH = True  # 启用权限预加载以提升性能

# SimpleUI 配置
SIMPLEUI_HOME_TITLE = "运维作业平台"
SIMPLEUI_HOME_ICON = "fas fa-server"
SIMPLEUI_LOGO = "https://cdn-icons-png.flaticon.com/512/1087/1087815.png"  # 齿轮图标

# SSH 连接配置
SSH_TIMEOUT = 30
SSH_CONNECT_TIMEOUT = 10
SSH_MAX_RETRIES = 3

# 使用Redis作为Session后端
SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "default"
SESSION_COOKIE_AGE = 60 * 60 * 8  # 8h
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = False  # 如果使用HTTPS，设置为True
SESSION_COOKIE_SAMESITE = 'Lax'

# CORS 配置
CORS_ALLOW_ALL_ORIGINS = True  # 仅在开发环境中使用
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]


# 验证码配置
CAPTCHA_ENABLED = False  # 是否启用验证码
CAPTCHA_IMAGE_SIZE = (120, 40)  # 验证码图片大小
CAPTCHA_LENGTH = 4  # 验证码长度
CAPTCHA_TIMEOUT = 5  # 验证码超时时间（分钟）
CAPTCHA_FONT_SIZE = 28  # 字体大小
CAPTCHA_BACKGROUND_COLOR = '#ffffff'  # 背景颜色
CAPTCHA_FOREGROUND_COLOR = '#333333'  # 前景颜色
CAPTCHA_FILTER_FUNCTIONS = (
    'captcha.helpers.post_smooth',
)
# 验证码字符集（只使用数字和大写字母，避免混淆）
CAPTCHA_CHALLENGE_FUNCT = 'captcha.helpers.random_char_challenge'
CAPTCHA_MATH_CHALLENGE_OPERATOR = '+'  # 数学验证码操作符


# 日志配置
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '%(levelname)s %(asctime)s %(module)s %(process)d %(thread)d %(message)s',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
        'simple': {
            'format': '%(levelname)s %(message)s',
        },
        'standard': {
            'format': '[%(asctime)s] %(levelname)s [%(name)s:%(lineno)s] %(message)s',
            'datefmt': '%Y-%m-%d %H:%M:%S'
        },
        'json': {
            '()': 'pythonjsonlogger.jsonlogger.JsonFormatter',
            'format': '%(asctime)s %(levelname)s %(name)s %(lineno)d %(message)s',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'standard',
        },
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'django.log',
            'maxBytes': 1024*1024*50,  # 50MB
            'backupCount': 5,
            'formatter': 'standard',
            'encoding': 'utf-8',
        },
        'error_file': {
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'error.log',
            'maxBytes': 1024*1024*50,  # 50MB
            'backupCount': 5,
            'formatter': 'standard',
            'encoding': 'utf-8',
        },
        'security_file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'security.log',
            'maxBytes': 1024*1024*50,  # 50MB
            'backupCount': 10,
            'formatter': 'json',
            'encoding': 'utf-8',
        },
        'axes_file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'axes.log',
            'maxBytes': 1024*1024*20,  # 20MB
            'backupCount': 5,
            'formatter': 'standard',
            'encoding': 'utf-8',
        },
        'celery_file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'celery.log',
            'maxBytes': 1024*1024*50,  # 50MB
            'backupCount': 5,
            'formatter': 'standard',
            'encoding': 'utf-8',
        },
        'ssh_file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'ssh.log',
            'maxBytes': 1024*1024*30,  # 30MB
            'backupCount': 5,
            'formatter': 'standard',
            'encoding': 'utf-8',
        },
        'mail_admins': {
            'level': 'ERROR',
            'filters': ['require_debug_false'],
            'class': 'django.utils.log.AdminEmailHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'level': 'INFO',
        'handlers': ['console', 'file'],
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['error_file', 'mail_admins'],
            'level': 'ERROR',
            'propagate': False,
        },
        'django.security': {
            'handlers': ['security_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'axes': {
            'handlers': ['axes_file', 'security_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'celery': {
            'handlers': ['celery_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'celery.task': {
            'handlers': ['celery_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'hosts.ssh_manager': {
            'handlers': ['ssh_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'executor.services': {
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': False,
        },
        'scheduler.tasks': {
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': False,
        },
        'accounts.models': {
            'handlers': ['security_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'permissions.services': {
            'handlers': ['security_file'],
            'level': 'INFO',
            'propagate': False,
        },
        # 应用级别的日志记录器
        'hosts': {
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': True,
        },
        'job_templates': {
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': True,
        },
        'executor': {
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': True,
        },
        'scheduler': {
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': True,
        },
        'script_templates': {
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': True,
        },
        'quick_execute': {
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': True,
        },
        'accounts': {
            'handlers': ['security_file'],
            'level': 'INFO',
            'propagate': True,
        },
        'permissions': {
            'handlers': ['security_file'],
            'level': 'INFO',
            'propagate': True,
        },
        'dashboard': {
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}
