# Generated by Django 5.0.1 on 2026-07-12 10:18

from django.db import migrations, models


def enforce_signed_agent_servers(apps, schema_editor):
    AgentServer = apps.get_model('agents', 'AgentServer')
    AgentServer.objects.exclude(shared_secret='').update(require_signature=True)
    AgentServer.objects.filter(shared_secret='').update(is_active=False)


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0030_agent_agent_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentserver',
            name='require_signature',
            field=models.BooleanField(default=True, verbose_name='是否强制签名校验'),
        ),
        migrations.RunPython(enforce_signed_agent_servers, migrations.RunPython.noop),
    ]