# Generated by Django 5.0.1 on 2026-06-08 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executor', '0009_rename_exec_rec_ct_obj_type_created_idx_executor_ex_content_1978b4_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executionrecord',
            name='execution_type',
            field=models.CharField(choices=[('quick_script', '快速脚本执行'), ('quick_file_transfer', '快速文件传输'), ('job_workflow', 'Job工作流执行'), ('scheduled_job', '定时作业执行'), ('flow_node', '流程节点执行')], max_length=30, verbose_name='执行类型'),
        ),
    ]
