# Generated by Django 5.0.1 on 2026-06-08 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('executor', '0009_rename_exec_rec_ct_obj_type_created_idx_executor_ex_content_1978b4_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='流程名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('variables', models.JSONField(blank=True, default=dict, verbose_name='变量定义')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '流程模板',
                'verbose_name_plural': '流程模板',
                'db_table': 'flows_flow_template',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FlowRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '执行中'), ('success', '成功'), ('failed', '失败'), ('paused', '已暂停'), ('cancelled', '已取消')], default='pending', max_length=20)),
                ('trigger_type', models.CharField(default='manual', max_length=20, verbose_name='触发类型')),
                ('inputs', models.JSONField(blank=True, default=dict, verbose_name='输入')),
                ('outputs', models.JSONField(blank=True, default=dict, verbose_name='输出')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('started_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='执行人')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='flows.flowtemplate', verbose_name='流程模板')),
            ],
            options={
                'verbose_name': '流程执行实例',
                'verbose_name_plural': '流程执行实例',
                'db_table': 'flows_flow_run',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FlowNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=64, verbose_name='节点UUID')),
                ('name', models.CharField(max_length=200, verbose_name='节点名称')),
                ('node_type', models.CharField(choices=[('script', '脚本执行'), ('file_transfer', '文件传输'), ('job_plan', '作业执行方案'), ('manual', '人工确认'), ('condition', '条件分支'), ('parallel', '并行网关'), ('join', '汇聚网关')], max_length=32, verbose_name='节点类型')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='节点配置')),
                ('position', models.JSONField(blank=True, default=dict, verbose_name='画布位置')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='flows.flowtemplate', verbose_name='流程模板')),
            ],
            options={
                'verbose_name': '流程节点',
                'verbose_name_plural': '流程节点',
                'db_table': 'flows_flow_node',
                'ordering': ['template', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FlowEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.JSONField(blank=True, default=dict, verbose_name='边条件')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='out_edges', to='flows.flownode', verbose_name='源节点')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_edges', to='flows.flownode', verbose_name='目标节点')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='flows.flowtemplate', verbose_name='流程模板')),
            ],
            options={
                'verbose_name': '流程边',
                'verbose_name_plural': '流程边',
                'db_table': 'flows_flow_edge',
            },
        ),
        migrations.CreateModel(
            name='FlowNodeRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '执行中'), ('success', '成功'), ('failed', '失败'), ('paused', '已暂停'), ('cancelled', '已取消')], default='pending', max_length=20)),
                ('inputs', models.JSONField(blank=True, default=dict, verbose_name='输入')),
                ('outputs', models.JSONField(blank=True, default=dict, verbose_name='输出')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('execution_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flow_node_runs', to='executor.executionrecord', verbose_name='关联执行记录')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flows.flownode', verbose_name='流程节点')),
                ('flow_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_runs', to='flows.flowrun', verbose_name='流程执行')),
            ],
            options={
                'verbose_name': '流程节点执行实例',
                'verbose_name_plural': '流程节点执行实例',
                'db_table': 'flows_flow_node_run',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['flow_run', 'status'], name='flows_flow__flow_ru_ad1a86_idx')],
                'unique_together': {('flow_run', 'node')},
            },
        ),
        migrations.AddIndex(
            model_name='flowrun',
            index=models.Index(fields=['template', 'status'], name='flows_flow__templat_657bba_idx'),
        ),
        migrations.AddIndex(
            model_name='flowrun',
            index=models.Index(fields=['started_by', 'created_at'], name='flows_flow__started_2281b5_idx'),
        ),
        migrations.AddIndex(
            model_name='flownode',
            index=models.Index(fields=['template', 'node_type'], name='flows_flow__templat_03fd45_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='flownode',
            unique_together={('template', 'uuid')},
        ),
        migrations.AddIndex(
            model_name='flowedge',
            index=models.Index(fields=['template', 'source'], name='flows_flow__templat_7a48c5_idx'),
        ),
        migrations.AddIndex(
            model_name='flowedge',
            index=models.Index(fields=['template', 'target'], name='flows_flow__templat_b34cf0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='flowedge',
            unique_together={('template', 'source', 'target')},
        ),
    ]
