# Generated by Django 5.0.1 on 2026-07-12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0002_alter_flownode_node_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='调度名称')),
                ('cron_expression', models.CharField(max_length=100, verbose_name='Cron表达式')),
                ('timezone', models.CharField(default='Asia/Shanghai', max_length=50, verbose_name='时区')),
                ('inputs', models.JSONField(blank=True, default=dict, verbose_name='启动变量')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_flow_schedules', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='flows.flowtemplate', verbose_name='流程模板')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_flow_schedules', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={'verbose_name': '流程定时调度', 'verbose_name_plural': '流程定时调度', 'db_table': 'flows_flow_schedule', 'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='FlowScheduleRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_for', models.DateTimeField(verbose_name='计划触发时间')),
                ('status', models.CharField(choices=[('starting', '启动中'), ('launched', '已启动'), ('failed', '启动失败')], default='starting', max_length=20, verbose_name='启动状态')),
                ('error_message', models.TextField(blank=True, verbose_name='启动错误')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('flow_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_runs', to='flows.flowrun', verbose_name='流程实例')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='flows.flowschedule', verbose_name='流程调度')),
            ],
            options={'verbose_name': '流程调度运行', 'verbose_name_plural': '流程调度运行', 'db_table': 'flows_flow_schedule_run', 'ordering': ['-scheduled_for']},
        ),
        migrations.AddConstraint(model_name='flowschedulerun', constraint=models.UniqueConstraint(fields=('schedule', 'scheduled_for'), name='flows_unique_schedule_minute')),
        migrations.AddIndex(model_name='flowschedule', index=models.Index(fields=['is_active', 'created_at'], name='flows_flow__is_acti_fc1ee9_idx')),
        migrations.AddIndex(model_name='flowschedule', index=models.Index(fields=['template', 'is_active'], name='flows_flow__templat_580be3_idx')),
        migrations.AddIndex(model_name='flowschedulerun', index=models.Index(fields=['schedule', '-scheduled_for'], name='flows_flow__schedul_dcf4d1_idx')),
        migrations.AddIndex(model_name='flowschedulerun', index=models.Index(fields=['status', '-scheduled_for'], name='flows_flow__status_83cc26_idx')),
    ]