/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AAlert: typeof import('@arco-design/web-vue')['Alert']
    ABadge: typeof import('@arco-design/web-vue')['Badge']
    AButton: typeof import('@arco-design/web-vue')['Button']
    ACard: typeof import('@arco-design/web-vue')['Card']
    ACheckbox: typeof import('@arco-design/web-vue')['Checkbox']
    ACol: typeof import('@arco-design/web-vue')['Col']
    ACollapse: typeof import('@arco-design/web-vue')['Collapse']
    ACollapseItem: typeof import('@arco-design/web-vue')['CollapseItem']
    ADescriptions: typeof import('@arco-design/web-vue')['Descriptions']
    ADescriptionsItem: typeof import('@arco-design/web-vue')['DescriptionsItem']
    ADivider: typeof import('@arco-design/web-vue')['Divider']
    AEmpty: typeof import('@arco-design/web-vue')['Empty']
    AIcon: typeof import('@arco-design/web-vue')['Icon']
    AInput: typeof import('@arco-design/web-vue')['Input']
    AInputSearch: typeof import('@arco-design/web-vue')['InputSearch']
    AModal: typeof import('@arco-design/web-vue')['Modal']
    AProgress: typeof import('@arco-design/web-vue')['Progress']
    ARow: typeof import('@arco-design/web-vue')['Row']
    ASpace: typeof import('@arco-design/web-vue')['Space']
    ASpin: typeof import('@arco-design/web-vue')['Spin']
    ASwitch: typeof import('@arco-design/web-vue')['Switch']
    ATable: typeof import('@arco-design/web-vue')['Table']
    ATableColumn: typeof import('@arco-design/web-vue')['TableColumn']
    ATabPane: typeof import('@arco-design/web-vue')['TabPane']
    ATabs: typeof import('@arco-design/web-vue')['Tabs']
    ATag: typeof import('@arco-design/web-vue')['Tag']
    ATextarea: typeof import('@arco-design/web-vue')['Textarea']
    ATree: typeof import('@arco-design/web-vue')['Tree']
    CDNMonacoEditor: typeof import('./components/CDNMonacoEditor.vue')['default']
    HostSelector: typeof import('./components/HostSelector.vue')['default']
    IconBulb: typeof import('@arco-design/web-vue/es/icon')['IconBulb']
    IconCheckSquare: typeof import('@arco-design/web-vue/es/icon')['IconCheckSquare']
    IconClose: typeof import('@arco-design/web-vue/es/icon')['IconClose']
    IconCloseCircle: typeof import('@arco-design/web-vue/es/icon')['IconCloseCircle']
    IconDown: typeof import('@arco-design/web-vue/es/icon')['IconDown']
    IconExclamationCircle: typeof import('@arco-design/web-vue/es/icon')['IconExclamationCircle']
    IconEye: typeof import('@arco-design/web-vue/es/icon')['IconEye']
    IconWifi: typeof import('@arco-design/web-vue/es/icon')['IconWifi']
    LightweightMonacoEditor: typeof import('./components/LightweightMonacoEditor.vue')['default']
    MonacoEditor: typeof import('./components/MonacoEditor.vue')['default']
    OptimizedMonacoEditor: typeof import('./components/OptimizedMonacoEditor.vue')['default']
    PermissionButton: typeof import('./components/PermissionButton.vue')['default']
    PermissionTable: typeof import('./components/PermissionTable.vue')['default']
    PermissionWrapper: typeof import('./components/PermissionWrapper.vue')['default']
    RealtimeLog: typeof import('./components/RealtimeLog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScriptEditorWithValidation: typeof import('./components/ScriptEditorWithValidation.vue')['default']
    SimpleMonacoEditor: typeof import('./components/SimpleMonacoEditor.vue')['default']
    SuccessModal: typeof import('./components/SuccessModal.vue')['default']
    TagEditor: typeof import('./components/TagEditor.vue')['default']
  }
}
